config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true
    validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "Postを投稿しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    def update
      if @post.update(post_params)
        redirect_to posts_path, notice: "Postを編集しました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice:"Postを削除しました！"
  end

  def confirm
    @post = Post.new(post_params)
    render :new if @post.invalid?
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twtapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header>
    <p>Twitter Clone App</p>
  </header>
</footer>
  <body>
    <%= yield %>
  </body>
<footer>
	<p>Copyright &copy; 2020 DIC.</p>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "Post一覧画面にもどる", posts_path %>

app/views/posts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>投稿内容:<%= @post.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit  "戻る", name: "back" %>
<% end %>

app/views/posts/edit.html.erb
  <h2>Postを編集する</h2>
  <%= render 'form' %>

app/views/posts/index.html.erb
<h1>Post一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>つぶやき</th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= link_to 'Postの詳細を確認する', post_path(post.id) %></td>
    <td><%= link_to "Postを編集する", edit_post_path(post.id),data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to 'Postを削除する', post_path(post.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しくPostを投稿する', new_post_path %>

app/views/posts/new.html.erb
  <h2>Postを作成する</h2>
  <%= render 'form' %>

app/views/posts/show.html.erb
<h1>投稿詳細画面</h1>
<p>内容: <%= @post.content %></p>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>